version: "3"

services:
  keycloak:
    # image: quay.io/keycloak/keycloak:latest
    image: jboss/keycloak
    ports:
      - "${KC_SERVER_PORT}:${KC_SERVER_DEFAULT_PORT}"
    environment:
      - KEYCLOAK_USER=${KC_SERVER_USER}
      - KEYCLOAK_PASSWORD=${KC_SERVER_PASSWORD}
      # - KEYCLOAK_IMPORT=/tmp/my_realm.json
      # - JAVA_OPTS="-Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.upload_scripts=enabled -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true"
    #   - KEYCLOAK_IMPORT={KC_IMPORT_FILE_FULL_PATH_GUEST}
    # volumes:
      # - ${KETCLOACK_DATA_PATH}:/tmp
      #   - ${KC_IMPORT_FILE_FULL_PATH_HOST}:${KC_IMPORT_FILE_FULL_PATH_GUEST}
    #   - conf_data:${KC_IMPORT_FILE_FULL_PATH_GUEST}
    #   - ${KC_IMPORT_FILE_LOCATION_PATH_HOST}:${KC_IMPORT_FILE_LOCATION_PATH_GUEST}

  app1:
    build:
      context: sso/keycloak-client/signon
      dockerfile: Dockerfile
    environment:
      - PORT=${APP1_PORT}
    ports:
      - "${APP1_PORT}:${APP1_PORT}"
    networks:
      - authnet

  app2:
    build:
      context: sso/keycloak-client/signon
      dockerfile: Dockerfile
    environment:
      - PORT=${APP2_PORT}
    ports:
      - "${APP2_PORT}:${APP2_PORT}"
    networks:
      - authnet

networks: 
  authnet:

# volumes:
#   conf_data:
# volumes:
#     - type: volume
#         source: keycloak_data
#         target: ${KETCLOACL_DATA_PATH}

# volumes:
#     keycloak_data:
#         driver: local
#         driver_opts:
#         type: bind
#         device: ${KETCLOACL_DATA_PATH}
